"""Migración inicial con User y Producto

Revision ID: 7aa5aff630f1
Revises: ce6b3f24b0bb
Create Date: 2026-03-05 09:06:05.971556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7aa5aff630f1'
down_revision = 'ce6b3f24b0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
