"""Agregar columna descripcion a Producto

Revision ID: ce6b3f24b0bb
Revises: d3040a0639a5
Create Date: 2026-03-05 09:00:30.406832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6b3f24b0bb'
down_revision = 'd3040a0639a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
